name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          npm ci
          cd examples
          npm ci
          cd ..
          npm test
