name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install deps & Playwright
        run: |
          npm ci
          npx playwright install --with-deps chromium
      - name: install examples deps
        run: |
          cd examples
          npm ci
          cd ..
      - name: Run tests
        run: npm test
